
cache: packages
sudo: false

language: python
python: 
  - 3.5
  - 3.6
#  - 3.7-dev

install:
  - pip install -r requirements.txt
script:
  - ./setup.py test

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

