
cache: packages
sudo: false

language: python
python: 
  - 3.5
  - 3.6
  - 3.7-dev # unclear if trusty supports 3.7

install:
  - pip install -r requirements.txt
script:
  - ./setup.py test

warnings_are_errors: false

allow_failures:
  - python: "3.7-dev"

notifications:
  email:
    on_success: change
    on_failure: change

