
cache: packages
os: linux
dist: bionic

language: python
python:
  - "3.9"
  - "3.7"
  - "3.8"

install:
  # workaround for 3.7-dev build error: ValueError: bad marshal data (unknown type code)
  - pip install -U distutils-pytest setuptools
  - #pip install -r requirements.txt
  - ./setup.py install
script:
  - ./setup.py test

warnings_are_errors: false

# matrix:
#   allow_failures:
#     - python: "3.7-dev"

notifications:
  email:
    on_success: change
    on_failure: change


